languages = ["english"]
authors = [
    "Andrzej Sapkowski",
    "Brandon Sanderson",
    "Travis Beacham",
    "Andrew Rowe",
    "Shirtaloon",
    "Tamsyn Muir",
    "James Islington",
    "Will Wight",
    "Christopher Paolini",
    "Matt Dinniman",
    "J. L. Mullins",
    "Selkie Myth",
    "Yrsillar",
    "Zogarth",
    "Azalea Ellis",
    "C. Mantis"
]